"""
Seed the database with the demo dataset used across the frontend:

    python manage.py seed_demo

Creates:
  • demo operator user (owner) + api token
  • the four agent configs (Search / Profile / Copywright / Responder)
  • app settings (company profile · ai key · frequent runs)
  • CRM content: leads, potentials, replies
  • one finished pipeline run so the dashboard has history
"""

from django.core.management.base import BaseCommand
from rest_framework.authtoken.models import Token

from core.models import AgentConfig, AppSettings, ChatMessage, EmailDraft, Lead, PipelineRun, Potential, Reply, User

DEMO_USERNAME = 'operator'
DEMO_PASSWORD = 'operator-demo-2026'

AGENT_DEFAULTS = {
    'search': {
        'db_provider': 'mongodb', 'db_name': '', 'db_connection': '',
        'api_url': 'https://example.com/discovery-api', 'api_auth': 'Bearer ••••',
        'system_prompt': (
            'You are the Search (Scrape) agent in an autonomous marketing & sales pipeline.\n'
            'Discover companies that match the ideal customer profile defined in Settings.\n'
            'Scrape public pages, extract company name, website, industry and contact signals,\n'
            'and emit each discovered company as a new LEAD for the pipeline.'
        ),
        'negative_prompt': (
            'Do not scrape gated, private or paywalled content.\n'
            'Do not store personal data beyond business contact signals.\n'
            'Do not invent companies or contacts that were not observed on the page.'
        ),
    },
    'profile': {
        'db_provider': 'mongodb', 'db_name': '', 'db_connection': '',
        'api_url': 'https://example.com/enrichment-api', 'api_auth': 'Bearer ••••',
        'system_prompt': (
            'You are the Profile agent.\n'
            'For every LEAD produced by Search (Scrape), build a structured company profile:\n'
            'size, industry, tech stack, likely pain points and a 0–100 fit score.\n'
            'Flag high-potential leads as POTENTIAL opportunities.'
        ),
        'negative_prompt': (
            'Do not infer sensitive attributes (health, politics, religion).\n'
            'Do not overwrite Search source data — enrich it.\n'
            'Do not assign a fit score without citing observed evidence.'
        ),
    },
    'copywright': {
        'db_provider': 'mongodb', 'db_name': '', 'db_connection': '',
        'api_url': 'https://example.com/send-api', 'api_auth': 'Bearer ••••',
        'system_prompt': (
            'You are the Copywright agent.\n'
            'Write a short, personalized first-touch email for each profiled lead,\n'
            'referencing the company profile from the Profile agent.\n'
            'One clear value proposition, one call to action, under 120 words.'
        ),
        'negative_prompt': (
            'No spam patterns: no "Dear Sir/Madam", no exclamation marks, no false urgency.\n'
            'No attachments or links in first-touch messages.\n'
            'Never mention that the message was generated by an AI.'
        ),
    },
    'responder': {
        'db_provider': 'mongodb', 'db_name': '', 'db_connection': '',
        'api_url': 'https://example.com/inbound-api', 'api_auth': 'Bearer ••••',
        'system_prompt': (
            'You are the Responder (Chatbot) agent.\n'
            'Handle replies from leads across email, LinkedIn and webchat.\n'
            'Answer questions using the company profile and approved messaging,\n'
            'book meetings when intent is clear, and escalate to a human when unsure.\n'
            'Log every exchange under REPLY in the CRM.'
        ),
        'negative_prompt': (
            'Never promise pricing, discounts or SLAs without approval.\n'
            'Do not argue with leads; de-escalate and offer a call instead.\n'
            'Do not continue a thread after an explicit opt-out.'
        ),
    },
}

LEADS = [
    ('Acme Robotics', 'Industrial automation', 'acmerobotics.io', 91, 'Search · scraped 42 pages', True),
    ('BlueRiver Finance', 'Fintech lending', 'blueriver.finance', 88, 'Search · industry index', True),
    ('Northwind Logistics', 'Supply chain & freight', 'northwindlogistics.com', 84, 'Search · scraped 34 pages', True),
    ('Orbit Health', 'HealthTech SaaS', 'orbithealth.ai', 82, 'Search · partner directory', True),
    ('Helios Energy', 'Renewables / solar', 'heliosenergy.com', 76, 'Search · conference list', True),
    ('Vantage Retail Group', 'E-commerce operations', 'vantage-retail.com', 71, 'Search · scraped 21 pages', True),
    ('Kestrel Manufacturing', 'Precision parts', 'kestrel-mfg.com', 64, 'Search / Scrape', False),
]

POTENTIALS = [
    ('Acme Robotics', 'Pilot — automated outreach for 3 sales regions', '$48,000', 'proposal', 'Copywright agent'),
    ('BlueRiver Finance', 'Quarterly lead-generation campaign', '$120,000', 'qualified', 'Profile agent'),
    ('Northwind Logistics', 'Profile-enrichment retainer', '$24,000', 'negotiation', 'Responder agent'),
    ('Helios Energy', 'Content engine subscription', '$60,000', 'qualified', 'Copywright agent'),
    ('Orbit Health', 'Responder integration pilot', '$36,000', 'discovery', 'Profile agent'),
]

REPLIES = [
    ('Acme Robotics', 'J. Meyer · Head of Growth', 'email', 'replied', 'Interested in a pilot — asked for pricing.'),
    ('BlueRiver Finance', 'S. Okafor · Ops Director', 'linkedin', 'meeting', 'Intro call booked for Thursday 14:00.'),
    ('Orbit Health', 'D. Lin · CTO', 'email', 'awaiting', 'Asked for security & compliance docs.'),
    ('Vantage Retail Group', 'P. Singh · CMO', 'email', 'replied', 'Requested a case study before deciding.'),
    ('Kestrel Manufacturing', 'R. Alvarez · Procurement', 'webchat', 'awaiting', 'Budget cycle question — draft pending.'),
]


class Command(BaseCommand):
    help = 'Seed the database with the demo dataset (idempotent)'

    def handle(self, *args, **options):
        # --- demo user (owner) -------------------------------------------
        user, created = User.objects.get_or_create(
            username=DEMO_USERNAME,
            defaults={'email': 'operator@agentic.local', 'role': User.Roles.OWNER, 'first_name': 'Operator'},
        )
        if created:
            user.set_password(DEMO_PASSWORD)
            user.save()
        token, _ = Token.objects.get_or_create(user=user)

        # --- agent configs ------------------------------------------------
        for agent, defaults in AGENT_DEFAULTS.items():
            AgentConfig.objects.get_or_create(agent=agent, defaults=defaults)

        # --- settings -----------------------------------------------------
        AppSettings.objects.get_or_create(pk=1, defaults={
            'company_name': 'Northstar Growth Partners',
            'company_website': 'https://northstargrowth.example.com',
            'company_description': 'B2B growth partner helping mid-market companies build predictable, '
                                   'AI-assisted outbound revenue engines.',
            'services': ['Lead generation', 'Outbound copywriting', 'Sales automation', 'Pipeline consulting'],
            'ai_provider': 'OpenAI',
            'runs_enabled': True,
            'run_frequency': '1h',
        })

        # --- CRM ----------------------------------------------------------
        if not Lead.objects.exists():
            for company, industry, website, score, source, profiled in LEADS:
                Lead.objects.create(
                    company=company, industry=industry, website=website,
                    score=score, source=source, profiled=profiled,
                )
            lead_by_name = {l.company: l for l in Lead.objects.all()}
            for company, opportunity, value, stage, owner in POTENTIALS:
                Potential.objects.create(
                    company=company, opportunity=opportunity, value=value,
                    stage=stage, owner_agent=owner, lead=lead_by_name.get(company),
                )
            for company, contact, channel, reply_status, summary in REPLIES:
                Reply.objects.create(
                    company=company, contact=contact, channel=channel,
                    status=reply_status, summary=summary,
                )
            PipelineRun.objects.create(
                triggered_by='seed',
                leads_created=0,
                potentials_created=0,
                replies_created=0,
                summary={'notes': ['Initial seed run — CRM populated from demo dataset'], 'agents': []},
            )
            ChatMessage.objects.get_or_create(
                role='ai',
                text='Responder online. I can summarize leads, draft outreach copy, or report on the last pipeline run.',
            )

            # --- EMAIL DRAFTS (OUTREACH) -----------------------------------
            lead_by_name = {l.company: l for l in Lead.objects.all()}
            EMAIL_DRAFTS = [
                {
                    'company': 'Acme Robotics',
                    'to_email': 'info@acmerobotics.io',
                    'subject': 'Quick idea for Acme Robotics',
                    'body': (
                        'Hi Acme Robotics team,\n\n'
                        'I was researching industrial automation companies and looked at '
                        'acmerobotics.io — a couple of things stood out:\n\n'
                        '• Not mobile-friendly (no viewport meta) → Mobile-first redesign offer\n'
                        '• Homepage loads slowly (4.2s) → performance audit: images, caching, CDN\n\n'
                        'We help teams fix exactly this (lead generation, outbound copywriting, '
                        'sales automation, pipeline consulting). '
                        'Worth a 15-minute call next week to walk through the top items?\n\n'
                        'Best,\nNorthstar Growth Partners'
                    ),
                    'findings': [
                        {'area': 'Mobile', 'severity': 'high',
                         'issue': 'Not mobile-friendly (no viewport meta).',
                         'recommendation': 'Mobile-first redesign offer — most of their traffic is on phones.'},
                        {'area': 'Performance', 'severity': 'medium',
                         'issue': 'Homepage loads slowly (4.2s).',
                         'recommendation': 'Propose a performance audit: image optimisation, caching, CDN.'},
                    ],
                    'status': EmailDraft.Statuses.DRAFT,
                },
                {
                    'company': 'Harbor & Co Catering',
                    'to_email': '',
                    'subject': 'Getting Harbor & Co Catering online',
                    'body': (
                        'Hi Harbor & Co team,\n\n'
                        'I couldn\'t find a working website for Harbor & Co Catering — which usually '
                        'means customers searching for you end up with competitors instead.\n\n'
                        'We build fast, search-ready sites for catering businesses '
                        '(lead generation, outbound copywriting, sales automation, pipeline consulting). '
                        'Would a 15-minute call next week be useful?\n\n'
                        'Best,\nNorthstar Growth Partners'
                    ),
                    'findings': [
                        {'area': 'Web presence', 'severity': 'high',
                         'issue': 'Has no website at all.',
                         'recommendation': 'Pitch an end-to-end website: domain, landing pages, SEO setup.'},
                    ],
                    'status': EmailDraft.Statuses.DRAFT,
                },
                {
                    'company': 'BlueRiver Finance',
                    'to_email': 'contact@blueriver.finance',
                    'subject': 'Quick idea for BlueRiver Finance',
                    'body': (
                        'Hi BlueRiver Finance team,\n\n'
                        'I was researching fintech lending companies and looked at blueriver.finance '
                        '— a couple of things stood out:\n\n'
                        '• Missing or too-short page title → on-page SEO: unique 50–60 char titles\n'
                        '• Homepage loads slowly → performance audit: images, caching, CDN\n\n'
                        'We help teams fix exactly this. Worth a 15-minute call next week?\n\n'
                        'Best,\nNorthstar Growth Partners'
                    ),
                    'findings': [
                        {'area': 'SEO', 'severity': 'high',
                         'issue': 'Missing or too-short page title.',
                         'recommendation': 'Pitch on-page SEO: unique 50–60 char titles per page.'},
                    ],
                    'status': EmailDraft.Statuses.SENT,
                    'sent_via': EmailDraft.Via.CONSOLE,
                },
            ]
            for draft_data in EMAIL_DRAFTS:
                lead = lead_by_name.get(draft_data['company'])
                EmailDraft.objects.create(
                    lead=lead,
                    company=draft_data['company'],
                    to_email=draft_data['to_email'],
                    subject=draft_data['subject'],
                    body=draft_data['body'],
                    findings=draft_data['findings'],
                    status=draft_data['status'],
                    sent_via=draft_data.get('sent_via', ''),
                )

        self.stdout.write(self.style.SUCCESS('Seed complete.'))
        self.stdout.write(f'  Demo user : {DEMO_USERNAME} / {DEMO_PASSWORD} (role: owner)')
        self.stdout.write(f'  API token : {token.key}')
