# Generated by Django 4.2.16 on 2026-09-25 12:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.CharField(choices=[('search', 'Search (Scrape)'), ('profile', 'Profile'), ('copywright', 'Copywright'), ('responder', 'Responder (Chatbot)')], max_length=20, unique=True)),
                ('db_provider', models.CharField(default='postgresql', max_length=20)),
                ('db_name', models.CharField(blank=True, max_length=200)),
                ('db_connection', models.CharField(blank=True, max_length=500)),
                ('api_url', models.CharField(blank=True, max_length=500)),
                ('api_auth', models.CharField(blank=True, max_length=500)),
                ('system_prompt', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
                ('model', models.CharField(default='GLM-4.6', max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_website', models.CharField(blank=True, max_length=300)),
                ('company_description', models.TextField(blank=True)),
                ('services', models.JSONField(blank=True, default=list)),
                ('ai_provider', models.CharField(default='OpenAI', max_length=50)),
                ('ai_key', models.CharField(blank=True, max_length=500)),
                ('runs_enabled', models.BooleanField(default=True)),
                ('run_frequency', models.CharField(choices=[('15m', 'Every 15 minutes'), ('1h', 'Every hour'), ('6h', 'Every 6 hours'), ('daily', 'Daily')], default='1h', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=300)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=300)),
                ('profiled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.CharField(default='manual', max_length=50)),
                ('summary', models.JSONField(default=dict)),
                ('leads_created', models.PositiveSmallIntegerField(default=0)),
                ('potentials_created', models.PositiveSmallIntegerField(default=0)),
                ('replies_created', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('linkedin', 'LinkedIn'), ('webchat', 'Webchat')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('replied', 'Replied'), ('awaiting', 'Awaiting'), ('meeting', 'Meeting booked')], default='awaiting', max_length=20)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Potential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=200)),
                ('opportunity', models.CharField(max_length=300)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('stage', models.CharField(choices=[('discovery', 'Discovery'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation')], default='discovery', max_length=20)),
                ('owner_agent', models.CharField(default='Profile agent', max_length=50)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potentials', to='core.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'Responder')], max_length=10)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
