# Generated by Django 4.2.16 on 2026-09-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='from_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_website',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=200)),
                ('to_email', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('sent_via', models.CharField(blank=True, choices=[('smtp', 'SMTP'), ('console', 'Console')], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='core.lead')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
