# Generated by Django 4.2.16 on 2026-09-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appsettings_from_email_appsettings_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
