# Generated by Django 4.2.16 on 2026-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lead_country_lead_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='report_email',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
