# Generated by Django 4.2.16 on 2026-10-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailtemplate_lead_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(default='autopilot', max_length=20)),
                ('action', models.CharField(max_length=60)),
                ('detail', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appsettings',
            name='autopilot_daily_limit',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='autopilot_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='auto_sent',
            field=models.BooleanField(default=False),
        ),
    ]
