# Generated by Django 4.2.16 on 2026-10-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activitylog_appsettings_autopilot_daily_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
