# Generated by Django 4.2.16 on 2026-10-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activitylog_appsettings_autopilot_daily_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='target_countries',
            field=models.TextField(blank=True),
        ),
    ]
