# Generated by Django 4.2.16 on 2026-10-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lead_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='rejected_domains',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
