# Generated by Django 4.2.16 on 2026-10-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appsettings_target_countries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='autopilot_daily_limit',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='autopilot_enabled',
        ),
        migrations.RemoveField(
            model_name='emaildraft',
            name='auto_sent',
        ),
    ]
