# Generated by Django 4.2.16 on 2026-10-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_appsettings_rejected_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='apollo_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
