# Generated by Django 4.2.16 on 2026-10-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_activitylog_and_more'),
        ('core', '0011_appsettings_apollo_api_key'),
    ]

    operations = [
    ]
